<a href="https://colab.research.google.com/github/irajamuller/quantum_computing/blob/main/N%C3%BAmeros_Complexos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from IPython.display import display, Math

In [9]:
# Declarando um número complexo
a = 2 + 3j
display(Math(f'{a}'))

<IPython.core.display.Math object>

In [12]:
b = 3 + 0j
c = -2j
print(c)

(-0-2j)


In [13]:
# Comparando dois números complexos
a = 1 + 2j
b = 1 + 2j
print(a == b)

True


In [17]:
# Extraindo parte real e parte imaginária
a = 10 + np.sqrt(2) * 1j
print(f'Parte real: {a.real}')
print(f'Parte imaginária: {a.imag}')

Parte real: 10.0
Parte imaginária: 1.4142135623730951


In [18]:
# Multiplicação de números complexos
a = 2 + 2j
b = 3 + 5j
print(f'a * b = {a * b}')

a * b = (-4+16j)


In [23]:
# Operação de conjugado complexo
a = 2 + 2j
b = np.conjugate(a)
print(f'Conjugado de a: {a.conjugate()}')
print(b.conjugate())

Conjugado de a: (2-2j)
(2+2j)


In [59]:
# Divisão de números complexos
x = 2 + 1j  # (c, d no cálculo do slide)
y = 3 + 2j  # (a, b no cálculo do slide)
print(f'x / y = {x / y}')
print(f'Real {(x.real * y.real + x.imag * y.imag) / (y.real ** 2 + y.imag ** 2)}') # 8 / 13
print(f'Real {(x.imag * y.real - x.real * y.imag) / (y.real ** 2 + y.imag ** 2)}') # 1 / 13

x / y = (0.6153846153846154-0.07692307692307691j)
Real 0.6153846153846154
Real -0.07692307692307693


In [33]:
# Vetor coluna (ket) e vetor linha (bra)
ket0 = np.array([ [1], [0] ])
bra0 = np.array([ [1, 0 ]])
print(ket0)
print(bra0)

[[1]
 [0]]
[[1 0]]


In [36]:
# Operação de complexo conjugado em um vetor/matriz
ket0 = np.array([ [1 + 2j], [4 -3j] ])
print(ket0)
print(ket0.conj())

[[1.+2.j]
 [4.-3.j]]
[[1.-2.j]
 [4.+3.j]]


In [37]:
# Operação de transposição em um vetor/matriz
ket0 = np.array([ [1 + 2j], [4 -3j] ])
print(ket0.T)

[[1.+2.j 4.-3.j]]


In [40]:
# Operação de dagger
ket0 = np.array([ [1 + 2j], [4 -3j] ])
bra0 = ket0.conjugate().T
print(bra0.conjugate().T)

[[1.+2.j]
 [4.-3.j]]


In [41]:
# Multiplicação por um escalar (k)
ket0 = np.array([ [1 + 2j], [4 -3j] ])
k = 2
print(k * ket0)

[[2.+4.j]
 [8.-6.j]]


In [50]:
a = np.array([ [1, 2, 3], [4, 5, 6] ])
b = np.array([ [7, 8], [9, 10], [11, 12] ])
print(a)
print(b)
print(a @ b)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]]


In [56]:
a = np.array([ [4, 7], [2, 6] ])
# print(np.linalg.inv(a))
# print(np.linalg.det(a))

a_1 = np.linalg.inv(a)
print(a @ a_1)


[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
